### ISSUE TITLE
Help in comparing integers

### ISSUE THREAD

**Issue by AlasailAlbusaidi** [AlasailAlbusaidi/SQA22F23449#1]
Can you please help me in comparing two integers in C?

**Comment by AlasailAlbusaidi** [comment]
you can use the following code to compare two integers:
#include <stdio.h>

int main() {
   int a, b;

   a = 11;
   b = 99;

   // to take values from user input uncomment the below lines −
   // printf("Enter value for A :");
   // scanf("%d", &a);
   // printf("Enter value for B :");
   // scanf("%d", &b);

   if(a > b)
      printf("a is greater than b");
   else
      printf("a is not greater than b");

   return 0;
}

**Comment by Ahad123884** [comment]
Try using the following code to compare two integers:
#include <stdio.h>

int main() {
   int a, b;

   a = 11;
   b = 99;

   // to take values from user input uncomment the below lines −
   // printf("Enter value for A :");
   // scanf("%d", &a);
   // printf("Enter value for B :");
   // scanf("%d", &b);

   if(a > b)
      printf("a is greater than b");
   else
      printf("a is not greater than b");

   return 0;
}
